
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdata_mover.h"

/*
* The configuration table for devices
*/

XData_mover_Config XData_mover_ConfigTable[XPAR_XDATA_MOVER_NUM_INSTANCES] =
{
	{
		XPAR_DATA_MOVER_0_DEVICE_ID,
		XPAR_DATA_MOVER_0_S_AXI_CONTROL_R_BASEADDR,
		XPAR_DATA_MOVER_0_S_AXI_CONTROL_BASEADDR
	},
	{
		XPAR_DATA_MOVER_1_DEVICE_ID,
		XPAR_DATA_MOVER_1_S_AXI_CONTROL_R_BASEADDR,
		XPAR_DATA_MOVER_1_S_AXI_CONTROL_BASEADDR
	},
	{
		XPAR_DATA_MOVER_2_DEVICE_ID,
		XPAR_DATA_MOVER_2_S_AXI_CONTROL_R_BASEADDR,
		XPAR_DATA_MOVER_2_S_AXI_CONTROL_BASEADDR
	}
};


